## Numpy

### NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [23]:
import numpy as np 

## create array using numpy 
## create a 1D array
arry1=np.array([1,2,3,4,5])
arry1


array([1, 2, 3, 4, 5])

In [26]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [27]:
np.array(a) ## convert to the one data type

array([1, 2, 3, 4, 5])

In [40]:
l= [[1,2,3,4],[1,2,3,4],[23,4,2,4]]
l

[[1, 2, 3, 4], [1, 2, 3, 4], [23, 4, 2, 4]]

In [41]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [23,  4,  2,  4]])

## Array generation function

In [44]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
arr1 = np.ones((6,6))
arr1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
## lin space 
arr3= np.linspace(0,1,100) ## first element and second is last element and last one is spacing we need
arr3

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Random Generation function

In [76]:
np.random.rand((10))

array([0.03525634, 0.72255374, 0.67249942, 0.20839384, 0.61281966,
       0.54738402, 0.05506955, 0.43098163, 0.95537928, 0.04854571])

In [88]:
np.random.randint(10,20,10) ## (minimum , maximum , Number of integers to generate)


array([17, 12, 15, 18, 14, 17, 18, 12, 17, 15])

## Array Attributes 

In [89]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr.shape

(3, 3)

In [93]:
arr.size

9

In [94]:
arr.dtype

dtype('int64')

In [96]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array Method

In [97]:
arr.min()

np.int64(1)

In [98]:
arr.sum()

np.int64(45)

In [102]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [103]:
arr.mean()

np.float64(5.0)

In [104]:
arr.std()

np.float64(2.581988897471611)

In [105]:
arr.argmax()

np.int64(8)

### Reshaping and resizing 

In [109]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [111]:
arr=arr.reshape(6,5)