# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [2]:
import numpy as np

In [2]:
array = np.random.randint(1,21,size =[5,5])
print("Original Array:")
print(array)

Original Array:
[[15 11  1  1  2]
 [10 19 16 11  5]
 [ 3  8  9  7 13]
 [ 3 12 20  1 15]
 [ 4 16  5 10 15]]


In [3]:
## Replace all the elements in the thrid column with 1. 
array[:,2] = 1
print(array)

[[15 11  1  1  2]
 [10 19  1 11  5]
 [ 3  8  1  7 13]
 [ 3 12  1  1 15]
 [ 4 16  1 10 15]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
arr= np.random.randint(1,17,size=(4,4))
print("Original Array:")
print(arr)

Original Array:
[[ 1  2  1  5]
 [ 9 14  3 13]
 [ 7  6 10 12]
 [ 2  5  4  7]]


In [5]:
## Replace the diagonal elements with 0.
np.fill_diagonal(arr,0)
print(arr)

[[ 0  2  1  5]
 [ 9  0  3 13]
 [ 7  6  0 12]
 [ 2  5  4  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [6]:
arr1= np.random.randint(1,37,size=(6,6))
print(arr1)

[[13 15  8 33 14 28]
 [22  3  4 27 22 32]
 [26 32 29 26 11 18]
 [ 4  3 34 22 22 19]
 [35 28 29 23 27 24]
 [ 2 14  2 18 12 22]]


In [7]:
# Extract the sub-array consiting of the 3rd to 5th rows and 2nd to 4th columns

sub_arr=arr1[2:5,1:4]
print(sub_arr)


[[32 29 26]
 [ 3 34 22]
 [28 29 23]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [8]:
def border(arr):
    rows,colm=arr.shape
    top=arr[0, :]
    bottom=arr[-1,:]
    left = arr[1:-1, 0]
    right = arr[1:-1, -1]
    return np.concatenate([top, right, bottom[::-1], left[::-1]])

In [9]:
arr=np.random.randint(1,26,size=(5,5))
print("Orginal arr")
print(arr)
print("Modified")
print(border(arr))


Orginal arr
[[ 5 11 21 23  8]
 [ 9  5  6 15 24]
 [22 15  8 18 12]
 [ 4 14 15 24 19]
 [ 7 13 20 23  6]]
Modified
[ 5 11 21 23  8 24 12 19  6 23 20 13  7  4 22  9]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [10]:
arr1= np.random.randint(1,13,size=(3,4))
arr2= np.random.randint(1,13,size=(3,4))
print("Array 1")
print(arr1)
print("Array 2")
print(arr2)

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

Array 1
[[ 5  6  5  1]
 [ 3  4 12  2]
 [ 8  7  2 10]]
Array 2
[[ 8  2  2  7]
 [ 9 12 11  6]
 [ 9  6  6  7]]


In [11]:


print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


Element-wise addition:
[[13  8  7  8]
 [12 16 23  8]
 [17 13  8 17]]
Element-wise subtraction:
[[-3  4  3 -6]
 [-6 -8  1 -4]
 [-1  1 -4  3]]
Element-wise multiplication:
[[ 40  12  10   7]
 [ 27  48 132  12]
 [ 72  42  12  70]]
Element-wise division:
[[0.625      3.         2.5        0.14285714]
 [0.33333333 0.33333333 1.09090909 0.33333333]
 [0.88888889 1.16666667 0.33333333 1.42857143]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [12]:
array=np.random.randint(1,17,size=(4,4))
print(array)

## Compute the row-wise and column-wise sum 

row_sum=np.sum(array,axis=1)
column_sum=np.sum(array,axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

[[ 4  6  5 15]
 [16 15  7 16]
 [ 1  6  7 15]
 [13  9 16  5]]
Row-wise sum:
[30 54 29 43]
Column-wise sum:
[34 36 35 51]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [13]:
array=np.random.randint(1,26,size=(5,5))
print("Array")
print(array)
## computing the mean , median,standard deviation and variacne of the array 

mean_value=np.mean(array)
median_value=np.median(array)
standard_deviation_value=np.std(array)
variance_array=np.var(array)

print(f"Mean:{mean_value}")
print(f"median:{median_value}")
print(f"Standard deviation:{standard_deviation_value}")
print(f"Variance of the array:{variance_array}")

Array
[[25  9 12  1  2]
 [10  4  4 16 11]
 [13 10 18  1  9]
 [12  9  6  6 17]
 [19 23 18 24 20]]
Mean:11.96
median:11.0
Standard deviation:7.039772723604079
Variance of the array:49.5584


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [20]:
array = np.arange(1,10).reshape(3,3)
print("Orginal Array:")
print(array)

#Normalize the array
mean=np.mean(array)
std_dev=np.std(array)
normolized_array=(array-mean) / std_dev
print("Normalized array:")
print(normolized_array)

Orginal Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [28]:
array=np.random.randint(1,10,size=(3,3))
row_array=np.random.randint(1,11,size=(3,))
print("Array")
print(array)
print()
print("1 D array")

print(row_array)

## Add the 1D array to each row of the 2D array using broadcasting
result=array+row_array
print()
print("Resulting array:")
print(result)



Array
[[3 2 7]
 [7 3 2]
 [3 8 8]]

1 D array
[9 9 7]

Resulting array:
[[12 11 14]
 [16 12  9]
 [12 17 15]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [32]:
array=np.random.randint(1,17,size=(4,4))
column_array=np.random.randint(1,17,size=(4,))

print("Array")
print(array)
print()
print("1 D array")

print(column_array)

## Add the 1D array to each column of the 2D array using broadcasting
result=array-column_array[:, np.newaxis]
print()
print("Resulting array:")
print(result)

Array
[[14  6 14 13]
 [ 8  9  6  3]
 [ 5 10  5  3]
 [12 11 16  6]]

1 D array
[ 3 12 11 16]

Resulting array:
[[ 11   3  11  10]
 [ -4  -3  -6  -9]
 [ -6  -1  -6  -8]
 [ -4  -5   0 -10]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [ ]:
matrix=np.random.randint(1,13,size=(3,3))
print("Orginal matrix")
print(matrix)

# compute the determinant 

derterminant = np.linalg.det(matrix)



Array
[[ 3  1 10]
 [ 9  4 11]
 [ 8  6  4]]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [3]:
matrix1=np.random.randint(1,7,size=(2,3))
matrix2=np.random.randint(1,7,size=(3,2))
print(matrix1)
print(matrix2)
# perform matrix multiplication 
result = np.dot(matrix1,matrix2)
print("Martrix multiplication result")
print(result)


[[4 4 1]
 [3 5 6]]
[[3 1]
 [1 2]
 [4 5]]
Martrix multiplication result
[[20 17]
 [38 43]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [5]:
# Create a Numpy array of shape (3,3) with values from 1 to 9 
array = np.arange(1,10).reshape((3,3))
print("Orignal array:")
print(array)

# Reshape the array to shape (1,9)
reshaped_array_1= array.reshape(1,9)
print(reshaped_array_1)
# Reshape the array to shape (9,1)
reshaped_array_2= reshaped_array_1.reshape((9,1))
print(reshaped_array_2)


Orignal array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [7]:
array= np.random.randint(1,21,size=(5,5))
print("Original array:")
print(array)

# Flatten the array
flattend_array = array.flatten()
print("Flattenend array:")
print(flattend_array)

# Reshape the array back to (5,5)
reshaped_array= flattend_array.reshape(5,5)
print("Reshaped array: ")
print(reshaped_array)


Original array:
[[15 16  3  5  4]
 [ 6 12 11  3 10]
 [19  1 16  8 10]
 [11  6  2  6 10]
 [17 15  5 11  9]]
Flattenend array:
[15 16  3  5  4  6 12 11  3 10 19  1 16  8 10 11  6  2  6 10 17 15  5 11
  9]
Reshaped array: 
[[15 16  3  5  4]
 [ 6 12 11  3 10]
 [19  1 16  8 10]
 [11  6  2  6 10]
 [17 15  5 11  9]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.



In [8]:
array = np.random.randint(1,21, size=(5,5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array 

corners = array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner elements:")
print(corners)

Original array:
[[13  8 18  3 10]
 [11 13 17 16 13]
 [18 20  3  7  2]
 [14  3  8 10 17]
 [ 2 18 12 16 16]]
Corner elements:
[13 10  2 16]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [9]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[ 7  6  4 19]
 [ 6 11 20  8]
 [ 5 10  5 14]
 [18 12  2 13]]
Modified array:
[[ 7  6  4 10]
 [ 6 10 10  8]
 [ 5 10  5 10]
 [10 10  2 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [10]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [11]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [12]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 1  4  6 17]
 [11  9 10 14]
 [ 5 20  9  2]
 [ 3  3 13 10]]
Masked array:
[[1 4 6 --]
 [-- 9 10 --]
 [5 -- 9 2]
 [3 3 -- 10]]
Sum of unmasked elements: 62


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [13]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 8  4 12]
 [17 10  6]
 [ 5 20  3]]
Masked array:
[[-- 4 12]
 [17 -- 6]
 [5 20 --]]
Modified masked array:
[[10  4 12]
 [17 10  6]
 [ 5 20 10]]
